### ISSUE TITLE
Convert to movie format

### ISSUE THREAD

**Issue by jopidioot** [nguyenquyhy/Flight-Recorder#100]
Hi,
Your adon is great and I want to use it for making flight movies via an editing program.
The recorded file format is .fltrec. Is their any way to convert it into a video format, that is recognisable for video editing programs, like Pinnacle? Than the recording can be edited. Looks great to me.

**Comment by nguyenquyhy** [comment]
The tool doesn't do screen recording, but there are many excellent tools for that in the market. I personally recommend OBS as it is free, efficient and has great support for layouts and plugins.
