### ISSUE TITLE
Import utility

### ISSUE THREAD

**Issue by jrfcs** [nguyenquyhy/Flight-Recorder#101]
First, thanks for providing export to CSV for analysis but is there a way to go back to the fltrec file format?   I would like to modify the data then import it back in to MSFS.

Has anyone written a convertor from CSV to fltrec?     thanks.

**Comment by jrfcs** [comment]
not really an issue.  It's a feature request

**Comment by nguyenquyhy** [comment]
I (and I think probably all GitHub users) actually use Issues to keep track of feature request also. I didn't see this Issue, so I created a new one from your discussion :) #104.
