### ISSUE TITLE
Buggy buttons interface when mouse hovering on them

### ISSUE THREAD

**Issue by olstr1kE** [nguyenquyhy/Flight-Recorder#105]
![issuescreenshot](https://user-images.githubusercontent.com/96101961/145938697-c1c2861b-9a35-4af3-85c1-5cda24e89806.jpg)

Buttons change to a buggy appearance when mouse cursor hover over them. They still work and appear when clicked on, but when hovering over with the mouse cursor, they change to this buggy appearance then change back to correct back and forth.

It was, with AIG Traffic Manager, the only application doing this on my computer. Made a system restore and no change to the issue.

**Comment by nguyenquyhy** [comment]
Please try again on the latest version and let me know if this still occurs.
