### ISSUE TITLE
Allways airliner on runway in replay-mode

### ISSUE THREAD

**Issue by transwarp20** [nguyenquyhy/Flight-Recorder#110]
Hi.
I allways recognize the following effect while beeing in replay mode in msfs:
On my home-airport EDLP allways a great airliner stands across on the runway, when approaching with replay-mode on.

At takeoff, there is definitely no AI-Traffic on the runway. Engaging the replay-mode after recording immediately shows an A320-like airliner across the middle of the runway which won't vanish till the end of the approach.

Any workaround?

**Comment by nguyenquyhy** [comment]
That is interesting. I have never noticed that, but I'll test again.

It is possibly that when starting replay, the tool resets the aircraft position to the starting point. MSFS might somehow think that the scenery is just loaded and put AI aircraft there.

**Comment by nguyenquyhy** [comment]
I tried this out but cannot reproduce. Do you use any traffic mod?

And what is your traffic setting?
![image](https://user-images.githubusercontent.com/1560418/210131965-aa852a21-75c2-43cb-b637-46bc20ff4335.png)
