### ISSUE TITLE
Movement reversed.

### ISSUE THREAD

**Issue by Totpie** [nguyenquyhy/Flight-Recorder#111]
At the time of replay, the movement of the aileron, stabilator and aircraft is reversed.
https://twitter.com/Totpie101/status/1576084572353499136?s=20&t=3RdZ0SESN2vCW57mCxQqDg

**Comment by nguyenquyhy** [comment]
I can finally fixed this thanks to a solution from @till213 (the creator of the excellent Sky Dolly replay software). The fix be released in an update this weekend.

**Comment by nguyenquyhy** [comment]
This is released in v0.24.
