### ISSUE TITLE
Stuttering when replay

### ISSUE THREAD

**Issue by Elekesey** [nguyenquyhy/Flight-Recorder#114]
With any aircraft, when the software is playing the replay, graphism are stuttering. That's not related with loading terrain. As soon the software is closed, instantly graphism are smooth like usual.

**Comment by nguyenquyhy** [comment]
Can you please give me more information?
- What happens exactly? Does it stutter only when moving the camera around, or even when camera is not moving? Does it happen for both cockpit and external view?
- Which aircraft do you see this issue on? Did the same happen in the built-in C152?
- What graphic setting do you use in the sim?
- What's your PC's specs (CPU, GPU, memory, storage)?

**Comment by Elekesey** [comment]
Thanks for your feedback.

- It stutter with any camera (fixed drone, moving drone, cockpit, external view, etc.).
- I tried with A330 from PMP, vanilla A320, built-in TBM930 and C152.
- Here are my Sim graphic settings :
![specs](https://user-images.githubusercontent.com/125213620/224580414-26631302-5d18-465f-ae47-1564a31fb41f.png)
- PC's specs :
_Processor : Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz, 3600 MHz, 8 core, 16 logical processor
RAM : 32,0 Go
Storage : Only 1 Crucial SSD 1TB CT1000MX500SSD1
Graphic : NVIDIA GeForce RTX 3070 / 8192Mo GDDR6 / DirectX 12_

Please check this video that I just made ; [https://we.tl/t-QWrO4ABZ1C](https://we.tl/t-QWrO4ABZ1C)
- From 0s to 5s, Flight Recorder 0.24.0.0 is running and Replay is started.
- At 5s, I clicked on "Stop Replay" so you can see it smooth again until the end (12s).

**Comment by Elekesey** [comment]
I've found what caused the issue. I used Flight Recorder from another local network computer (with a special configuration of SimConnect). If I launch Flight Recorder on the same PC than MSFS 2020 to record & replay, that works fine.

**Comment by nguyenquyhy** [comment]
Interesting. Do you mind sharing your SimConnect setup for that? I was trying to look for that.

**Comment by Elekesey** [comment]
Yes, of course.

On the MSFS2020 (Steam Edition) PC, you need to add this section in "C:\Users\<Your Username>\AppData\Roaming\Microsoft Flight Simulator\SimConnect.xml" :
`	<SimConnect.Comm>
		<Descr>Global IP Port</Descr>
		<Disabled>False</Disabled>
		<Protocol>IPv4</Protocol>
		<Scope>global</Scope>
		<Address>192.168.0.230</Address>
		<MaxClients>64</MaxClients>
		<Port>7421</Port>
		<MaxRecvSize>4096</MaxRecvSize>
		<DisableNagle>False</DisableNagle>
	</SimConnect.Comm>`

On the remote PC,

**Comment by nguyenquyhy** [comment]
Thank you for sharing the setup. 😄
