### ISSUE TITLE
.flightrecorder recovery

### ISSUE THREAD

**Issue by IFC-Pilot999** [nguyenquyhy/Flight-Recorder#115]
sent you a message on flightsim.to will attach file here. (.flightrecorder not supported by githubs file attatchments) Thanks.

https://drive.google.com/file/d/1GfeOXLvQhqbxNGsBEbtca8bKxEezfhhW/view?usp=sharing

**Comment by nguyenquyhy** [comment]
I have tried to use several tools to recover the file (it is actually a zip file), but none can 😢. Really sorry for that.

**Comment by IFC-Pilot999** [comment]
> I have tried to use several tools to recover the file (it is actually a zip file), but none can 😢. Really sorry for that.

No worries, it was worth a try regardless. Thank you for your time
