### ISSUE TITLE
Huge Issue with Game/Recorder

### ISSUE THREAD

**Issue by SkyCaptainJon** [nguyenquyhy/Flight-Recorder#120]
Hello. My name is Jonathan and I come from Sweden.
Ive been testing out this tool and have been very impressed with its capabilities, until a couple of days ago when a weird issue started. I couldnt figure out the reason for it first but have now narrowed it down to this mod and would like to know how i cleanly uninstall it so i can go from there. Windows cant find it as a program to uninstall and the issue persists if i remove the files.

Basically the issue is that since it started is that some planes seem burdened with absolutely rediculus weights, heavy enough that they can hardly take off (and i can tell because ive played this now quite a while) and there is always NO MATTER THE WEATHER an inexplicable storm level wind and horrible gusts that arnt affected by the weather settings. Like i said at first i didnt know what it was that caused it. At first i thought it could be on of the couple of got friends mods i have, BUT! Today the game offered me to start in safe mode with all the mods deactivaded and i happily did because i saw it as an opportunity to check what was upp. Suddenly all the planes flew fine. No abnormal weights and no absolutely rediculus soundless winds. BUT, during that session i descided to try this mod as it suddenly seemed like a possible candidate i could test without restarting the game and SUDDENLY, the issues where back.

Basically I just want to hear your advice and to know the best way to uninstall it. It seems to have a good reputation among most people so i just want a clean way to remove it so i can hopefully regain control over my game and work from there. Like i said if i just delete the files the issue persists. Its ONLY starting in safe mode that seems to work and that is UNTIL i start the program again.

Hope to hear from you soon, a couple of my planes are absolutely unplayable and the trim is slipping inexplicably on a lot of others :/ Its really concerning to me because i really like this game and have now spent quite a bit of money on it :/

Thanks beforehand and hope to hear from you soon.

Kind Regards.
Jonathan.

**Comment by nguyenquyhy** [comment]
There is no uninstallation because there is no installation. The tool doesn't put any files or make any change in your system other than the file you extracted. Not thing is run automatically if you doesn't run the tool yourself. If you don't like it, you can just delete the extracted folder.

If you don't run it and the issue still happens, it is from somewhere else unfortunately.

**Comment by SkyCaptainJon** [comment]
Oh :( That's bad news. Thanks I believe you, I guess it was just an unfortunate coincidence. Was really hoping this was it because then I had hope I could fix it.
Anyway thanks have a nice day.

**Comment by SkyCaptainJon** [comment]
I'm going to try reinstalling the game.
