### ISSUE TITLE
Flaps not visibly down

### ISSUE THREAD

**Issue by SoCalDude** [nguyenquyhy/Flight-Recorder#17]
During the recording of a landing, I used various levels of flaps. When replaying and viewing the landing from the drone camera, the flaps stayed in the retracted position the whole time.

Flight Recorder Version: **0.8.0.0**
Aircraft: **Cessna 172 Skyhawk (non-G1000)**

**Comment by nguyenquyhy** [comment]
Can you share the saved replay too?

**Comment by SoCalDude** [comment]
> Can you share the saved replay too?

It is the same replay file as in Issue #15.

**Comment by SoCalDude** [comment]
Here is a link to the video from which I recorded from the Flight Recorder playback...

[_https://youtu.be/WFMBG1oGy9Y_](https://youtu.be/WFMBG1oGy9Y)

**Comment by nguyenquyhy** [comment]
Can you still reproduce the flap issue? 
If you still can, can you let me know what is happening in the cockpit? Does the flap switch and the white indicator moving at all?
I have tried your replay several times and couldn't reproduce it.

By the way, do you have any physical flap handle (not the up/down switch)?

**Comment by SoCalDude** [comment]
I can try it again over the weekend. I do have a lever mapped to operate the flaps. When I use the lever, the animated lever in MSFS moves accordingly, as do the flaps. I could see if they didn't work at all, but different views of the same recording should be consistent.

Thanks for looking into this.

**Comment by nguyenquyhy** [comment]
It can only be consistent as far as all other surrounding context is consistent 😛. For example, if the level keep trying to set the flap level, it will fight with the replay and there is not much the tool can do about that. It becomes a timing issue that determine which value will get picked by the sim.

I'll try to note more about this in the description too.

**Comment by SoCalDude** [comment]
I was unable to reproduce my original flaps issue today. The flaps were as expected through multiple playbacks. I tried the C172 airplane (the one where I initially saw this issue) and the TBM-930.  You may close this issue.
