### ISSUE TITLE
Flight Recorder crashing when loading a file

### ISSUE THREAD

**Issue by Davedon2021** [nguyenquyhy/Flight-Recorder#24]
I'm having the same problem. I've saved my file and when I press 'Load' it takes me to the file directory, I select the saved file to open, I go back to MSFS and the Flight Recorder is gone. I reopen Flight Recorder and go through the same process, the 'replay' is not active. 'Record' and 'Save' and 'Replay' all work before the file is saved, after that problems exist. Any ideas?
I tried to attach the .csv file but GitHub community won't accept it on this chatline saying they don't support the file type.

**Comment by nguyenquyhy** [comment]
It shouldn't be CSV. The Export to CSV function is to allow you to open the file in Excel to analyze your flight.

You should press Save button and save it to a .flightrecorder file.

**Comment by Davedon2021** [comment]
That was the issue, everythings working perfectly now.  Thanks for the
quick response, this is a superior addon, thanks so much for your help and
hardwork on this.
Very Much appreciated.
Dave W

**Comment by nguyenquyhy** [comment]
Anyway I have improved this and it will show an error message instead of crashing 😄.

**Comment by Davedon2021** [comment]
Thanks!

**Comment by nguyenquyhy** [comment]
Released in v0.10
