### ISSUE TITLE
Stuttering when using any screen recording

### ISSUE THREAD

**Issue by gibboireland** [nguyenquyhy/Flight-Recorder#29]
Hi there,

Kudos on a great app - super impressive and easy to use! App works incredibly well with no FPS drops that I can see during flight recording or playback. Use of the app on screen is perfect.

However, when using any screen capturing, even at the highest settings (lossless) such as OBS, Xbox Game Bar and others - major stuttering and juddering can be seen. It happens at all stages including take off, during flight, landing and when on the ground. This only seems to be the case in recordings. Never seen anything like this before, but thought best to post here. Example in the file attached.

Thanks for any help as to how to possibly overcome - recording your vids Id imagine is the primary use case for this! Thanks :)

https://user-images.githubusercontent.com/71132831/109025554-bce23980-76b6-11eb-9485-683155b08984.mp4

**Comment by gibboireland** [comment]
[Main.zip](https://github.com/nguyenquyhy/Flight-Recorder/files/6037151/Main.zip)

**Comment by nguyenquyhy** [comment]
This is very strange. I did not have this issue or heard about this before.

Can you please provide me with some additional information?

1. Are you using version 0.9?
1. When you replay and record with OBS/Game Bar, can you check Task Manager to see if CPU or Memory is near 100% and how much CPU/Memory is Flight Recording consuming?
1.  Which aircraft are you testing with?

**Comment by gibboireland** [comment]
Thanks for the quick reply. 100% using 0.9 -  just downloaded it again from FlightSim.to.
Computer resources never maxed at all - high spec machine.
Tested with C172 with default livery at EINN (not heavy graphic wise or many buildings).

Here is a short video just to show you all the above again I just put together. Unlisted link:
https://youtu.be/Fs0L9lYsPgY

Again - just to repeat - on screen, this works flawlessly. When you see the recording, is when all this stuttering appears....

**Comment by nguyenquyhy** [comment]
Does that mean it looks fine in OBS preview window and only get the issue in the recorded mp4?

**Comment by gibboireland** [comment]
I only have the one screen, but I didnt check OBS preview yet. But its not an OBS issue - as tried with different recording software too. YouTube is processing that vid so should be ready very shortly for you to view.

**Comment by nguyenquyhy** [comment]
Not saying it is OBS issue 😅, but since OBS has the preview window, it is a bit easier to find out which stage causing the stutter than Game Bar.

Just want to confirm a few information
1. Does it stutter in the sim?
2. Does it stutter in OBS preview window? (you can Alt+Enter to switch MSFS to window mode to see both MSFS and OBS at the same time)
3. Can you attach a screenshot of OBS Settings > Output > Recording?

**Comment by gibboireland** [comment]
Hi there, please go ahead and close this issue. I have pinpointed it to OBS as recording via GeForce works fine. Big thanks for your responsiveness in replying/assisting with my request, and congrats on a fantastic product once again!
