### ISSUE TITLE
Some suggestions for improvements

### ISSUE THREAD

**Issue by PatriceCesson** [nguyenquyhy/Flight-Recorder#30]
Hi,

Here are some ideas for improvements:

1. At the end of the record, propose directly to save the file in order not to loose the recording (but the user may cancel).
2. When recording is active, add a big red indicator (that turns to grey when no recording) to indicate that recording is active 
3. During replay, mix the 2 keys "Pause"/"Resume" into one key: When replay is active, the key would be labelled "Pause Replay", When replay is paused the key would be labelled "Resume Replay". Possible to add also a big Green indicator when replay is running (indicator turns grey when paused / stopped).
4. Add the file name being replayed in the window (maybe in the title or elsewhere)

Thanks.

**Comment by nguyenquyhy** [comment]
I split this into several issues for better tracking and close this one for now.
1. #35 
2. I am not too fond of red, but I'll add some indicator #14 
3. I prefer to have separate buttons. I don't like clicking on the same location would have different results. I would probably not make this change until the UI becomes too cramped.
4. #36 #2
