### ISSUE TITLE
Total time of replay does not match recording?

### ISSUE THREAD

**Issue by nguyenquyhy** [nguyenquyhy/Flight-Recorder#37]

**Comment by kaosfere** [comment]
Hi there.   I just came here to post an issue, but I think this may be a reference to it already?   I was doing some testing of flight recorder tools yesterday, and I noticed that Flight Replay seemed to replay a good bit "faster" than the events it recorded.   I performed a number of tests, but to confirm this in particular I recorded a timed run down a long runway, then timed a playback of the recording and it ended up being about 20% faster.

I posted a thread about this at [AvSim](https://www.avsim.com/forums/topic/596330-flight-recorder-comparison-video/), and you can see the difference about[ six minutes into this comparison video](https://www.youtube.com/watch?v=yN4JxwogIV0&t=5m57s) I recorded.

**Comment by nguyenquyhy** [comment]
Yes I saw the post so I created this issue to make sure I don't forget 😂 . Do you by any chance have the .flightrecorder file for that flight? That would help a lot in figuring out the issue.

**Comment by kaosfere** [comment]
For sure, here you go.    If you run a stopwatch from the time the parking brake is released until the brakes go on at the opposite threshold, it should come out to about 2 minutes.  In reality it was closer to 2 minutes and 30 seconds.


[dragrace.zip](https://github.com/nguyenquyhy/Flight-Recorder/files/6063013/dragrace.zip)

**Comment by kaosfere** [comment]
Also, should you want it, this is the log of the test flight that I made in the video I linked you to.

[testflight.zip](https://github.com/nguyenquyhy/Flight-Recorder/files/6063022/testflight.zip)

**Comment by nguyenquyhy** [comment]
When looking at the data, the start is at frame 221, which has the timing of 45s and the crossing of threshold is at frame 6507 with timing of 165s. So the replay is working correctly, and the problem seems to be from recording.

This is very weird since the recording doesn't do anything other than logging down the timing. I'll do some more tests on this.

**Comment by kaosfere** [comment]
Sounds good.   If I can help with testing in any way, let me know.

**Comment by nguyenquyhy** [comment]
Hmm I just did several other recording and couldn't reproduce the issue.

Are you able to retest this? Best is without any other replay tools other than Flight Recorder.

**Comment by nguyenquyhy** [comment]
Also, are you by any chance overclocking your CPU?

**Comment by nguyenquyhy** [comment]
I checked the data of testflight.zip too. The data shows the flight of 63s, which is exactly what is in the video. 

Are you able to help me to record a video that include both the recording and replaying and attach the .flightrecorder file? That would help me tremendously since I cannot reproduce this issue on my PC...

**Comment by kaosfere** [comment]
For sure.   As long as I have time tonight, I can do another run like that and record both the original and the replay for you.  I'll post here when I've got it.

**Comment by nguyenquyhy** [comment]
Thanks, really appreciate that.

**Comment by kaosfere** [comment]
I was just looking at a CSV export (I love that feature, btw) to see what data you capture, thinking it might be helpful if I time between two events you can easily see in the flight record.   It looks like if I run the timer between when I release the parking brake and when I turn it back on that should be pretty straight forward for you to examine in the data, if that works for you.

**Comment by nguyenquyhy** [comment]
Yes releasing the parking brake or leaving the ground are pretty easy to see from both video and the data, so either of that would work.

**Comment by kaosfere** [comment]
Hello again.    Oddly, when I tried to capture the problem again yesterday I was unable to reproduce it.   I tried a number of different ways, but each time the replay time was resolutely the same as the original recording time.   I'm truly not sure what to make of that, I'll try a little more testing today.    But it's possible I happened to capture a transient problem that's since resolved itself.

Frustrating, but probably better on your end.  :D   I'll follow up after more testing.

**Comment by nguyenquyhy** [comment]
I guess you can also try when running multiple recording tools at the same time. Maybe there is some conflicts. But I really can't think of anyway the timing can be wrong since the tool maintain an external clock and stick to that clock regardless what happen in the sim.

**Comment by nguyenquyhy** [comment]
I'll close this for now. Feel free to reopen if you can get more information on this.
