### ISSUE TITLE
Unable to manipulate cameras in replay

### ISSUE THREAD

**Issue by stuieH** [nguyenquyhy/Flight-Recorder#40]
Whilst running replay I switched to the Drone view, but then was unable to change the view using my assigned buttons/keys and also was unable to switch view back to cockpit or external view.  Is there a way to manipulate camera views when in replay mode or must one set the view before starting Replay?

**Comment by nguyenquyhy** [comment]
I don't think this issue is related to Flight Recorder. The tool doesn't touch any camera functionality of the sim.

**Comment by nguyenquyhy** [comment]
I'll close this for now. If you have any additional information, please feel free to add and reopen.
