### ISSUE TITLE
Improvement request: Save the recording properly when we close the sim, in case the user forgot to save it

### ISSUE THREAD

**Issue by PatriceCesson** [nguyenquyhy/Flight-Recorder#42]
Hi,

This is a problem I am facing relatively often:

During a flight, when it comes to landing, I start a record of the landing via Flight Recorder..

Once done, I do the landing (very busy activity) and often after all has been done, I close the SIM. But I forgot (too late!) that I had a recording running! and what happens is that the recording is lost as Flight Recorder closes also.

A suggestion woulld be, on such a situation, that Flight Recorder proposes to save the recording file to the user before closing too, and as a result the record file will be saved.

The solution may be either to ask the user to save the record (Same as Save button) or save it directly with a name and a timestamp and advising the details of the file being created.

Thanks.

Patrice.

**Comment by nguyenquyhy** [comment]
Just to give you some additional information, the recording isn't lost when you close the sim, it was just hidden. If you open the sim again, it will show back up, allowing you to replay or save.

I will definitely improve on this. The blank screen when the sim is not running is a bit of a safe guard for the first few versions, but it will change soon. 

There will also be some warning messages when you are about to do something that can lead to lost recording (e.g. closing the tool or start new recording before saving).

**Comment by PatriceCesson** [comment]
Ok.
Thank you.

Provenance : Courrier pour Windows 10

De : Nguyễn Quý Hy
Envoyé le :mardi 2 mars 2021 21:45
À : nguyenquyhy/Flight-Recorder
Cc : PatriceCesson; Author
Objet :Re: [nguyenquyhy/Flight-Recorder] Improvement request: Save therecording properly when we close the sim, in case the user forgot to save it(#42)

Just to give you some additional information, the recording isn't lost when you close the sim, it was just hidden. If you open the sim again, it will show back up, allowing you to replay or save.
I will definitely improve on this. The blank screen when the sim is not running is a bit of a safe guard for the first few versions, but it will change soon.
There will also be some warning messages when you are about to do something that can lead to lost recording (e.g. closing the tool or start new recording before saving).

**Comment by nguyenquyhy** [comment]
Released a confirmation prompt in v0.11
