### ISSUE TITLE
Non MSFS 2020 aircraft

### ISSUE THREAD

**Issue by Joshbear11** [nguyenquyhy/Flight-Recorder#44]
I have the Spitfire plane but when I playback the recording it shows as one of the standard MSFS planes. Is this a known issue?

Thanks

**Comment by nguyenquyhy** [comment]
Do you have a video recording or something showing what you are experiencing? It sounds really weird since the sim doesn't load the aircraft for you.

**Comment by Joshbear11** [comment]
HI
Thanks for coming back.  Good news today it worked and showed the spitfire.   Will come back if it changes.  Thanks

Josh

**Comment by nguyenquyhy** [comment]
I'll close this for now.
