### ISSUE TITLE
Ran great the first time. Now I cannot get it to open and run, even as Run As Administrator

### ISSUE THREAD

**Issue by BitTron213** [nguyenquyhy/Flight-Recorder#45]
So I had downloaded the .exe file and ran it. It opened just fine. I then ran FS2020 and the Flight Recorder worked fine.

However, the next time I went to use it with FS2020, the Flight Recorder .exe would not open or run, even when selecting it to 'Run as Administrator'. I even ran FS2020, and once that was launched I tried to then run the Flight Recorder .exe file, but again, it would not open or run.

What's the problem here? I didn't try re-loading the .exe and running it again. Do I need to do that? Is there a known reason for this issue? (I'm running this on a Win-10 Pro OS)

**Comment by nguyenquyhy** [comment]
Did you extract the folder before running? You can't run it directly insize the zip file.

If you have already extracted the folder, most likely something on your computer corrupted some files inside. Easiest way is just to unzip again.

**Comment by BitTron213** [comment]
Ok, I'll try that.
  
  
   
  
  
   Thanks so much.
  
  
   
    On 03/06/2021 8:52 PM Nguyễn Quý Hy <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   Did you extract the folder before running? You can't run it directly insize the zip file.
   If you have already extracted the folder, most likely something on your computer corrupted some files inside. Easiest way is just to unzip again.

**Comment by nguyenquyhy** [comment]
Close this for now. Please feel free to comment if you still have the issue.

**Comment by BitTron213** [comment]
I still CANNOT get it to work!
  
  
   
  
  
   When I try and run FlightRecorder.Client.exe (selecting it to run by Administrator) it opens a box and says "Cannot connect to SimConnect!"
  
  
   
  
  
   Do I need to run FS2020 first? Then run this .exe file?
  
  
   
  
  
   Also, do you have the download link, where I can try to redownload it again and try re-running it or re-installing it?
  
  
   
  
  
   Thanks for any additional help you can provide.
  
  
   
  
  
   THIS, BTW, is one of the most --NEEDED-- features for FS2020!
  
  
   
  
  
   Mark Dundon
  
  
   
  
  
   --
  
  
   
    On 03/14/2021 3:55 PM Nguyễn Quý Hy ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Close this for now. Please feel free to comment if you still have the issue.

**Comment by BitTron213** [comment]
Ok, never mind, I found the link to DL the install file again, so I'll try re-downloading it, extracting it, and re-running it.
  
  
   
  
  
   And I will let you know.
  
  
   
  
  
   Thanks again,
  
  
   
  
  
   Mark Dundon
  
  
   
  
  
   --
  
  
   
    On 03/14/2021 3:55 PM Nguyễn Quý Hy ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Close this for now. Please feel free to comment if you still have the issue.

**Comment by BitTron213** [comment]
Ok, I did re-download and run the Flight Recorder and it ran fine.
  
  
   
  
  
   Two questions though ....
  
  
   
  
  
   On the playback it started from the beginning, but I notices that the playback slider was grayed out and the speed box, which was set to x1 was also grayed out.
  
  
   
  
  
   So even though it played back the entire flight just fine, all I wanted to do is take a look at my initial take off and final approach and landing.
  
  
   
  
  
   So my questions are 1) Why was the slider and speed box grayed out? and 2) Is there a way to speed up the replay or move to a specific portion of the replay?
  
  
   
  
  
   I love your add-on to FS2020, but not being able to select which portion of the playback to watch or speed it up, is a huge drawback.
  
  
   
  
  
   Is there something wrong with my installation of this?
  
  
   
  
  
   Thanks for your help.
  
  
   
  
  
   Mark D.
  
  
   
  
  
   ---
  
  
   
    On 03/14/2021 3:55 PM Nguyễn Quý Hy ***@***.***> wrote:
   
   
    
   
   
    
   
   
   Close this for now. Please feel free to comment if you still have the issue.

**Comment by nguyenquyhy** [comment]
> 1) Why was the slider and speed box grayed out? and 2) Is there a way to speed up the replay or move to a specific portion of the replay?

You can just start the replay and then pause it to use the slider or the speed. At some point in the future I will allow sliding before replaying #52, but right now that is not supported.
