### ISSUE TITLE
Undercarriage Down

### ISSUE THREAD

**Issue by warthog02** [nguyenquyhy/Flight-Recorder#53]
Thanks Quy Hy for the recorder.

After landing I started the replay. The aircraft undercarriage remained down during the replay. Does that mean that the recorder must be retracted before stopping the recording and commencing replay?

**Comment by nguyenquyhy** [comment]
Can I have more info on this?
- Which aircraft is it?
- Any video you can share?
- Can you also share the .flightrecorder file so I can try it out?

The recorder should record/replay gear position and gear handle.

**Comment by warthog02** [comment]
[flightrecorder20210313.log](https://github.com/nguyenquyhy/Flight-Recorder/files/6136241/flightrecorder20210313.log)
I think the above is the recorder file. Aircraft is the FlyingIron Spitfire for MSFS. Please see the replay recorded using XBox Game Bar here https://youtu.be/apSdFd56QxY .
Thanks for your kind reply.

**Comment by nguyenquyhy** [comment]
I don't really need the log file. I need the saved .flightrecorder file because I don't have that aircraft to test myself.

I think I saw the gear replay properly before, but that was before the aircraft update. Or maybe I was just mistaken.

**Comment by warthog02** [comment]
Will try another flight later to see the result. Thanks.

**Comment by warthog02** [comment]
I have done a takeoff and the replay showed the gear being retracted.
Haven't succeeded in landing yet 'cos I kept stalling after takeoff while
trying circuits. Will report soon when I have a good recording of gear
extension. I believe the aircraft must be having power on, door and canopy
closed before replaying and if it is after a landing the gear will be down
when a replay is started. Will report here when I've done another recording.

--
Attan Akmar

**Comment by warthog02** [comment]
Hi Quy Hy

I've done some circuits and landings in the Spitfire and managed to
configure the aircraft prior to each playback so that I have the gear,
door, canopy and flaps in the right position for the animation to work
perfectly. I now use your app for every flight that I make.

Thanks for the great application and the support you have provided.


--
Attan Akmar

**Comment by nguyenquyhy** [comment]
I'll close it for now then. Please let me know if it happens again.

**Comment by warthog02** [comment]
Thanks.  It certainly won't happen again as I now know how to avoid if
happening.
