### ISSUE TITLE
"Cannot connect to Simconnect!"

### ISSUE THREAD

**Issue by Aulaum** [nguyenquyhy/Flight-Recorder#69]
I installed the app, unzipped the folder and moved it into a separate folder where I keep my FS apps. Once I started the sim and opened the app, it said "Cannot connect to Simconnect!".
I also noticed that my flight recorder file didn't have a ".exe".
Could anyone please help me?

**Comment by nguyenquyhy** [comment]
That is strange. You should see the exe file like this:
![image](https://user-images.githubusercontent.com/1560418/112909734-01029880-90c0-11eb-9f98-cf033c3a9087.png)

I would guess that your antivirus mistakenly deleted the exe. Are you able to check on that?

**Comment by nguyenquyhy** [comment]
Oh wait but you said you can start the app, how did you start it without the exe though? I guess you do have the exe, just that the extension is hidden.

**Comment by nguyenquyhy** [comment]
About the "Cannot connect to SimConnect" issue, do you happen to have any of my other app (e.g. Flight Events, Flight Tracker Stream Deck)? If you do, do you encounter the same SimConnect error?

I really want to know if other software that uses SimConnect would work so I can figure out if this is a problem with SimConnect installation or with Flight Recorder itself. Right now I don't have any clue about this issue, but I really want to resolve it.

**Comment by Aulaum** [comment]
Thanks for answering that quickly! Yes, I can start the app. No, I do not have other addons. I will be able to send a screenshot when I'm home.

**Comment by Aulaum** [comment]
![16171344528793225492507108317628](https://user-images.githubusercontent.com/81478530/113048995-6ed3c080-91a3-11eb-9e81-34092c941ec0.jpg)
![Uploading 16171344712714965367614019664040.jpg…]()

**Comment by parkingbrake** [comment]
I have the same issue, and no Chance to start this program. Can bot connect to the sim connect. I try older versions but its even the same issue. Cant connect to simconnect.
Pherhaps you can Help me 🙂

**Comment by Aulaum** [comment]
Update: I reinstalled the flight simulator and it still doesn't work.

**Comment by nguyenquyhy** [comment]
I would guess that there is something blocking SimConnect installation (automatically by the sim) in your PC. I am still waiting for the Dev Q&A platform from Microsoft to go live so that I can ask the dev if there is anyway we can troubleshoot this.

**Comment by Aulaum** [comment]
Thank you so much for the help.
I installed the FS via Disc. Maybe that's the issue.

**Comment by pamartz-62** [comment]
Hello @nguyenquyhy I am having this exact same problem. Whenever I launch FlightRecorder.Client.exe, its main window appears and it displays the message "Cannot connect to Simconnect! Please start Microsoft Flight Simulator." on the top area of the window for a few seconds, then immediately the app ends. I have other apps that make use of Simconnect.dll, e.g. LittleNavMap and they work. I tried copying Simconnect.dll to the FlightRecorder folder, with no success. My Windows system and MSFS installation are in Spanish language (ES). Every day I try to start Flight Recorder, a FlightRecorder log file is created empty, with 0 bytes size. Do you think I can try anything to solve my issue? Thanks!

**Comment by nguyenquyhy** [comment]
@pamartz-62 I already have a fix for this, but I realize I haven't released the fix yet. Do you mind pinging me (Hy) in my Discord server (https://discord.gg/azqQrWWEbV) so that I can verify if the fix works?

**Comment by nguyenquyhy** [comment]
Released in v0.20

**Comment by pamartz-62** [comment]
Perfect, thank you very much!!
