### ISSUE TITLE
Landing gear issue also on Carenado Mooney Ovation

### ISSUE THREAD

**Issue by jctarvin** [nguyenquyhy/Flight-Recorder#70]
I am recording my flights not only in Flight Recorder 0.11.1.0 but also through Nvidia. Don't know if this is related/cause of the issue.

Already reported the problem in Just Flight Arrow III, so I switched aircraft to the Mooney Ovation (latest version). Same issue, the landing gear stays down during the entire flight when playing back through the Flight Recorder. Also, even though external aircraft lights are turned on, they didn't show up in the Flight Recorder playback. 

I may be doing something wrong here. I just want to replay takeoffs and landings from different views and show the gear coming up and going down.

Thanks!!!

**Comment by nguyenquyhy** [comment]
If you can reproduce this issue, would you please save the replay into a .flightrecorder file and attach it here? It would help greatly for me to see what was happening.

**Comment by jctarvin** [comment]
Nguyen,

I think I've discovered the issue....me! I've found that if I save the flightrecorder file, then load it into flightrecorder after restarting the flight in MSFS2020, everything replays just fine. 

Have done this with both Mooney and Just Flight Arrow III. 

THANK YOU for your responsiveness and a great application for MSFS2020!!

⁣John​


-------- Original Message --------

**Comment by nguyenquyhy** [comment]
I'll close this issue and will track this in #68. I do want to try out a fix for this in the next update.
