### ISSUE TITLE
as soon as it starts, everything stops 

### ISSUE THREAD

**Issue by claudio2739** [nguyenquyhy/Flight-Recorder#80]
It used to be fine before. Now as soon as it starts everything freezes, fps at 2. Even the mouse jerks! Help me!

**Comment by nguyenquyhy** [comment]
Can you check Task Manager to see CPU and Memory consumption of Flight Recorder, and send me the .log files in Flight Recorder folder?

**Comment by claudio2739** [comment]
sorry I'm not very practical and I don't know how to do what you asked me. the flight recorder consumes 2/3% of cpu but I don't know how to send you the data. thanks anyway

**Comment by nguyenquyhy** [comment]
I would guess that there is something interfering the communication between the tool and the sim, probably antivirus. Can you try to turn on the FPS in MSFS Dev mode and see it it is really 2-3FPS? I guess it just looks sluggish because the tool can't send data to the sim quickly. One more thing to try is that after you click Replay, click back into MSFS so MSFS is the active window. Windows sometimes does some deprioritization on inactive software.

You can also ping me (Hy) in my Discord server to troubleshoot this. https://discord.gg/azqQrWWEbV

**Comment by claudio2739** [comment]
Update: flightrecorder only works if it is not superimposed on the game (stay on top). Somehow so I can use it. ;-)

**Comment by nguyenquyhy** [comment]
I don't really understand the last comment 😂, but I guess you are saying that the replay looks laggy when Flight Recorder is in focus (or active). If so, yes you should always have MSFS active during replay so it can get the highest priority from the system.

**Comment by claudio2739** [comment]
I'm writing to you in Italian, I don't know how Google translates into English! :-D When I use the "stay on top" button and I see the flightrecorder window superimposed on the simulator, this doesn't work (it jerks). If I leave the flightrecorder window on the desktop "under" the simulator then it's ok! However, I hope that everything will be resolved with the next updates! ;-) P.s. where do you write from?

**Comment by nguyenquyhy** [comment]
Yah this should be just some Windows setting affecting prioritization based on what is on top. 
On my PC there is no issue doing what you described https://youtu.be/EkL-FY4qcSE .

Have you tried turning on Game Mode? And are you using any other game optimization (or "booster") software?

**Comment by claudio2739** [comment]
Even on my PC it worked just fine before like you. :-( Anyway if I put it "under" it's fine! Anyway don't worry it will be a problem of my pc ... I have the game mode and I don't have other active programs (oops ... I didn't understand that you are the developer of this mod !!! Great !! :-D)
