### ISSUE TITLE
График полёта пишется, а видео нет? 

### ISSUE THREAD

**Issue by Algor63** [nguyenquyhy/Flight-Recorder#82]
![Снимок экрана (89)](https://user-images.githubusercontent.com/84025023/117825671-2f0af900-b278-11eb-8520-67efd26cf7ff.png)
График полёта пишется, а видео нет?

**Comment by nguyenquyhy** [comment]
Flight Recorder only replay the flight inside the sim 😀. If you want to record videos, you can try many free one such as OBS.

**Comment by Algor63** [comment]
А как это, воспроизвести  полет внутри сима ,сделать?

**Comment by nguyenquyhy** [comment]
You can find many demo on YouTube. Here is one for example: https://youtu.be/OUHlePjNxk8?t=132

**Comment by Algor63** [comment]
Огромное спасибо, разобрался, всё получилось.
 
 
 
--
Александр Горяев
