### ISSUE TITLE
Landing Gear not deployed when landing

### ISSUE THREAD

**Issue by pepparino** [nguyenquyhy/Flight-Recorder#90]
Been trying this replay with the stable version of the A32NX mod and it just floats with its engines and when you stop the replay, the plane will crash if its on the ground cause the gear is not deployed and I cant do anything

![189560610_151921913583119_6493726418862409127_n](https://user-images.githubusercontent.com/84753205/119436465-ca0ed300-bd4e-11eb-9412-5053ff38b023.png)

**Comment by nguyenquyhy** [comment]
Are you able to attach the recorded file too?

**Comment by pepparino** [comment]
Well I did what yo

u told me to do but github still doesn't accept it even if I compressed it into a zip file

**Comment by mustard27** [comment]
I have the same problem, the landing gear is invisible. i can hear it going out, you can see the lever in the down position, but not visually.

Note: I stopped my replay once the aircraft (tbm930) was stopped on the parking and cut everything sytem (engine and all electric board system). is it the reason ?

**Comment by nguyenquyhy** [comment]
Yes that is the reason. If you shutdown the aircraft, you have to turn it on before replay.
