### ISSUE TITLE
Heading indicator turns incorrectly

### ISSUE THREAD

**Issue by socorrista22198** [nguyenquyhy/Flight-Recorder#91]
Hello! I didn´t try with another plane, but with the Cessna C-152, the Heading indicator turns at the double speed that it should. For example, i like to record the take off at runway 35, so i start recording, i take off and i turn 90º to follow the route at 80º. Now I alt+tab, stop recording, and press the Replay button to watch the take off. While i'am watching the turn, the heading indicator becames crazy, doesn´t show the real heading that i see at the compass. When the playback finish and the program gives me the control, my heading indicator shows 170º, when it should be at 80º.

I dont know if someone more have this issue.

Cheers! thanks for this awesome tool :)

**Comment by nguyenquyhy** [comment]
Yes I notice this issue as well. I suspect this is because the tool replays both magnetic heading and true heading (as I am not sure which one MSFS expects), and probably confuses some of MSFS calculation. I'll test around a bit more later.

**Comment by nguyenquyhy** [comment]
Released in 0.20
