### ISSUE TITLE
ATC Violation

### ISSUE THREAD

**Issue by rea139** [nguyenquyhy/Flight-Recorder#93]
When you start the replay, ATC calls "You are not authorize to take off" , this happens every time I replay my landings, which is what I use and like your tool, not a game breaker.

**Comment by nguyenquyhy** [comment]
Yes unfortunately the sim has no idea that is it being replayed, and there is no way for the plugin to tell the sim so because since there is no built-in replay support. You'll need to either turned off ATC or request clearance manually while replaying.
